version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      custom_net:
        ipv4_address: 10.5.0.5
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    expose:
      - "3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  backend:
    container_name: backend
    build: ./backend
    networks:
      custom_net:
        ipv4_address: 10.5.0.6
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

# Exposes React App on local network
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

